spring:
  profiles:
    active: default
  application:
    name: discovery-service
---
spring:
  profiles: default
  cloud:
    config:
      uri: ${vcap.services.config-server.credentials.uri:http://localhost:8888}
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://localhost:8761}/eureka/
server:
  port: 8761
management:
  security:
    enabled: false