spring:
  profiles:
    active: default
  application:
    name: config-server
---
spring:
  profiles: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kbastani/todo-service-config
          basedir: target/config
server:
  port: 8888
management:
  security:
    enabled: false