
---
resources:
- name: todo-core
  type: git
  source:
    uri: https://github.com/kbastani/qcon-nyc-2017
    branch: master
    paths:
    - ./todo-core
- name: todo-ui
  type: git
  source:
    uri: https://github.com/kbastani/qcon-nyc-2017
    branch: master
    paths:
    - ./todo-ui
jobs:
- name: todo-ui
  max_in_flight: 1
  plan:
  - get: todo-ui
    trigger: true
  - task: prepare
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: alpine
      inputs:
        - name: todo-ui
      outputs:
        - name: artifact
      run:
        path: sh
        args:
        - -exc
        - |
          cd todo-ui/todo-ui \
          && mvn clean package \
          && mv target/todo-ui*.jar ../../artifact/todo-ui.jar
  - task: deployment
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: concourse/cf-resource
          tag: latest
      inputs:
      - name: artifact
      - name: todo-ui
      run:
        path: sh
        args:
        - -exc
        - |
          cf api $api \
          && cf login -u $username -p $password -o $organization -s $space \
          && cf rename $current_app_name $current_app_name-existing \
          && cf push $current_app_name -p $path -f $manifest --no-start \
          && cf start $current_app_name \
          && cf map-route $current_app_name $domain --hostname $host \
          && cf delete -f $current_app_name-existing
    params:
      path: artifact/todo-ui.jar
      current_app_name: todo-ui
      host: todo-ui
      domain: cfapps.io
      manifest: todo-ui/todo-ui/manifest.yml
      api: {{pws-api}}
      username: {{pws-username}}
      password: {{pws-password}}
      organization: {{pws-org}}
      space: {{pws-space}}
- name: todo-core
  max_in_flight: 1
  plan:
  - get: todo-core
    trigger: true
  - task: build
    file: todo-core/deployment/tasks/build-core.yml
  - task: deployment
    file: todo-core/deployment/tasks/deploy-core.yml
    params:
      path: artifact/todo-core.jar
      current_app_name: todo-core
      host: todo-core
      domain: cfapps.io
      manifest: todo-core/todo-core/manifest.yml
      api: {{pws-api}}
      username: {{pws-username}}
      password: {{pws-password}}
      organization: {{pws-org}}
      space: {{pws-space}}